version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - redis

    #command: php artisan serve --host=0.0.0.0 --port=8000
    #command: bash -c "php artisan migrate && php artisan db:seed && apache2-foreground"
    command: bash -c "apache2-foreground"
    networks:
      - backend
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_WAIT_TIMEOUT=28800  
      - MYSQL_MAX_ALLOWED_PACKET= 128M
    networks:
      - backend
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - backend

networks:
  backend: